// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RevercePOCO
{

    // Clients
    public partial class Client
    {
        public int ClientId { get; set; } // ClientID (Primary key)
        public string FirstName { get; set; } // FirstName (length: 50)
        public string LastName { get; set; } // LastName (length: 50)
        public System.DateTime Birthday { get; set; } // Birthday
        public string Phone { get; set; } // Phone (length: 20)

        // Reverse navigation

        /// <summary>
        /// Child Cards where [Cards].[ClientID] point to this entity (FK_Cards_Clients)
        /// </summary>
        public System.Collections.Generic.ICollection<Card> Cards { get; set; } // Cards.FK_Cards_Clients

        public Client()
        {
            Cards = new System.Collections.Generic.List<Card>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
