// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace RevercePOCO
{

    // Operations
    public partial class Operation
    {
        public int OperationId { get; set; } // OperationID (Primary key)
        public string OutId { get; set; } // OutID (length: 16)
        public string InId { get; set; } // InId (length: 16)
        public decimal Amount { get; set; } // Amount
        public System.DateTime OperationTime { get; set; } // OperationTime

        // Foreign keys

        /// <summary>
        /// Parent Card pointed by [Operations].([InId]) (FK_Operations_Cards1)
        /// </summary>
        public Card In { get; set; } // FK_Operations_Cards1

        /// <summary>
        /// Parent Card pointed by [Operations].([OutId]) (FK_Operations_Cards)
        /// </summary>
        public Card Out { get; set; } // FK_Operations_Cards
    }

}
// </auto-generated>
